// <auto-generated />
using System;
using CountriesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountriesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CountriesAPI.Models.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("capital")
                        .HasColumnType("longtext");

                    b.Property<string>("currency_code")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("estimated_gdp")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("exchange_rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("flag_url")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_refreshed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("population")
                        .HasColumnType("bigint");

                    b.Property<string>("region")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("currency_code");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("region");

                    b.ToTable("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
